# theme: jekyll-theme-minimal
# title: Hi, I'm An!
# description: Hi! I’m currently a software engineer in the Bay Area. As a minority in the tech field, I have a commitment to tackling diversity and inclusion, and I’m working towards surrounding myself with people who sees the importance of this as well.
# I recently graduated from Brown University with a double concentration in Computer Science and Applied Mathematics, all while being a varsity athlete.
